name = "webhook-typer"
vars = { ENVIRONMENT = "production" }
type = "javascript"

account_id = ""
zone_id = ""

routes = [
  "typedwebhook.tools/webhook/*",
  "typedwebhook.tools/ws/*",
  "typedwebhook.tools/new_webhook"
]

compatibility_date = "2022-02-11"
compatibility_flags = []

kv_namespaces = [
  { binding = "SESSIONS", id = "8f972cab743647288e47bf12a11b8e66" }
]

[durable_objects]
bindings = [
  { name = "WEBSOCKETS", class_name = "WebSocketStore" }
]

[[migrations]]
tag = "v1"
new_classes = ["WebSocketStore"]

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[miniflare]
durable_objects_persist = true

[env.staging]
name = "webhook-typer-staging"
workers_dev = true
route = "webhook-typer-staging.inngest.workers.dev/*"
vars = { ENVIRONMENT = "staging" }
